# Page tree!!!目录
nav:
  - "开始→": "index.md"
  
  - "1. 关于社区": "about/index.md"
  
  - "2. 基本功能":
      - "basic/index.md"
      - "2.1 注册&登录": "basic/2.1.注册&登录.md"
      - "2.2 主界面": "basic/2.2.主界面.md"
      - "2.3 发帖页": "basic/2.3.发帖页.md"
      - "2.4 帖子页": "basic/2.4.帖子页.md"
      - "2.5 小黑屋": "basic/2.5.小黑屋.md"
      - "2.6 个人设置": "basic/2.6.个人设置.md"
      - "2.7 第三方登录": "basic/2.7.第三方登录.md"
      
  - "3. 高级功能":
      - "advanced/index.md"
      - "3.1 私密主题": "advanced/3.1.私密主题.md"
      - "3.2 文件&照片上传": "advanced/3.2.文件照片上传.md"
      - "3.3 将社区安装为应用（PWA）": "advanced/3.3.pwa.md"

  - "4. 实用工具&技术信息":
      - "4.1 DNS解析流程图（暂未完成）": "info/4.1.dns解析流程图（暂未完成）.md"
      - "4.2 从微信里转存自定义表情包": "info/4.2.转存表情包.md"
      - "社区运行状态": "https://stats.uptimerobot.com/ZOuWPrYNjt"
      - "图标库搜索": "info/iconsearch.md"
      - "[管理员]Microsoft Clarity 社区统计": "https://clarity.microsoft.com/projects/view/krvl9qsy2g/dashboard"
      
  - "最后←": "end.md"
  
  - "社区准则": "about/社区准则.md"
  
  - "社区问题反馈": "https://www.bravely.pp.ua/d/88"
  
  - "↹回到社区↹": "https://www.bravely.pp.ua"


# ↓
# ↓
# ↓
# ↓
# ↓
# ↓
# ↓
# ↓


# 配置
# Project information
site_name: "Always Bravely Docs"
site_description: "Always Bravely! | 文档"
site_author: "Always Bravely Community Team"
site_url: "https://docs.bravely.pp.ua/"

# Copyright
copyright: "&copy; 2024-Now Always Bravely Community Team. All rights reserved."

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/html5syt/Always-Bravely-Docs"
edit_uri: "edit/main/docs"

#[UI]
theme:
  name: material
  custom_dir: docs/custom
  # font:
  #   text: Bitter
  #   code: Roboto Mono
  logo: assets/icon.png
  # https://s2.loli.net/2024/02/01/gaE47y5fKM6kosV.png
  favicon: assets/icon.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 关闭自动模式
    #primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: blue grey # 上方的
      accent: blue # 链接等可交互元件的高亮色
      # teal 
      toggle:
        icon: material/brightness-4 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black 
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-7
        name: 切换至日间模式
  features: 
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.instant.progress
    # - navigation.prune #渲染的 HTML 中仅包含可见的导航项
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate 
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github #右上角图标
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      Mkdocs: octicons/tag-16    
    

extra:
  generator: true  #已更改：修订日期与版本号显示，在custom/partial/copyright处更改。
  social:
    - icon: fontawesome/brands/weixin
      link: /assets/tim.png
      name: weixin
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1172199422 #联系方式
      name: Bilibili
    - icon: fontawesome/brands/github
      link: https://github.com/html5syt
      name: Github
    - icon: fontawesome/regular/envelope
      link: mailto:<bravely@bravely.pp.ua> #联系方式
      name: Email



plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - offline
  - glightbox
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: iso_date
      enable_creation_date: true
      fallback_to_build_date: true
      # exclude:
        # - index.md 

  - git-committers:
      enabled: !ENV [CI, false]
      repository: html5syt/Always-Bravely-Docs
      branch: main
      exclude:
        - index.md 

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - callouts
  - md_in_html
  - markdown.extensions.abbr # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
      toc_depth: 6
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

  
extra_javascript:
  # - assets/javascripts/extra.js 
  - assets/javascripts/bannerSlider.js
  - assets/javascripts/mathjax.js
  - assets/javascripts/iconsearch.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra_css:
  - assets/css/extra.css
  - assets/css/customize.css  #按钮圆角化
  - assets/css/bannerSlider.css
  - https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-webfont/1.7.0/style.css  #字体 
  # - assets/font2/font.css #YRDZST
  

watch:
  - docs
  - mkdocs.yml
  - docs/custom/partials